directory: \\Datengrab\Musik

# Required Python modules (pip install):
# pyacoustid python3-discogs-client requests
plugins: embedart fetchart ftintitle chroma discogs zero importadded inline rewrite spotify deezer
threaded: yes

# Clean up: We won't need READMEs, cover files et cetera anymore.
clutter: ["Thumbs.DB", ".DS_Store", ".m3u", ".png",
          ".jpg", ".nfo", ".txt", ".log", ".gif", ".url",
         ]

paths:
  default: $albumartist/$album/%if{$multidisc,CD $disc/}$track. $title
  singleton: $artist/$title
  comp: $artist/$album/$track. $title

import:
  move: yes
  resume: yes
  autotag: yes
  incremental: yes
  languages: en de jp ru

# -----------------------
# General plugins:

embedart:
  # Don't keep cover.jpeg
  remove_art_file: yes

zero:
  # Clean the tags from nonsense cruft
  fields: month day genre comments lyrics
  comments: [EAC, LAME, from.+collection, 'ripped by', 'bandcamp.com']
  update_database: true

importadded:
  preserve_mtimes: yes
  preserve_write_mtimes: yes

item_fields:
  # We only use "CD <n>" when there is actually a CD 2.
  multidisc: 1 if disctotal > 1 else 0

rewrite:
  # Unify artist names.
  artist 잠비나이: Jambinai
  artist Ciolkowska: Циолковская
  artist Koenjihyakkei: Kōenji Hyakkei

# -----------------------
# Source plugins (with Spotify having less priority because it is not quite
# as good as Deezer in my tests):

discogs:
   source_weight: 0.0

deezer:
   source_weight: 0.0

spotify:
   source_weight: 0.5
   mode: open
